#!/bin/bash

# ------------------ WEASEL WORDS ------------------

echo -e "\033[1;32mChecking for weasel words...\033[0m"

weasels="many|various|very|fairly|several|extremely\
|exceedingly|quite|remarkably|few|surprisingly\
|mostly|largely|huge|tiny|((are|is) a number)\
|excellent|interestingly|significantly\
|substantially|clearly|vast|relatively|completely"
 
wordfile=""
 
# Check for an alternate weasel file
if [ -f $HOME/.words ]; then
    wordfile="$HOME/.words"
fi
 
if [ -f $WORDSDIR/weasels ]; then
    wordfile="$WORDSDIR/weasels"
fi
 
if [ -f words/weasels ]; then
    wordfile="words/weasels"
fi
 
if [ ! "$wordfile" = "" ]; then
    weasels="xyzabc123";
    for w in `cat $wordfile`; do
        weasels="$weasels|$w"
    done
fi
 
 
if [ "$1" = "" ]; then
 echo "usage: `basename $0` <file> ..."
 exit
fi

egrep -i -n --color "\\b($weasels)\\b" $*

weaselcount=0
for arg in $*; do
    weaselhere=$(egrep -i -c "\\b($weasels)\\b" $arg)
    weaselcount=$((weaselcount + weaselhere))
done

# ----------------- PASSIVE VOICE --------------------

echo -e "\033[1;32mChecking for passive voice...\033[0m"

irregulars="awoken|\
been|born|beat|\
become|begun|bent|\
beset|bet|bid|\
bidden|bound|bitten|\
bled|blown|broken|\
bred|brought|broadcast|\
built|burnt|burst|\
bought|cast|caught|\
chosen|clung|come|\
cost|crept|cut|\
dealt|dug|dived|\
done|drawn|dreamt|\
driven|drunk|eaten|fallen|\
fed|felt|fought|found|\
fit|fled|flung|flown|\
forbidden|forgotten|\
foregone|forgiven|\
forsaken|frozen|\
gotten|given|gone|\
ground|grown|hung|\
heard|hidden|hit|\
held|hurt|kept|knelt|\
knit|known|laid|led|\
leapt|learnt|left|\
lent|let|lain|lighted|\
lost|made|meant|met|\
misspelt|mistaken|mown|\
overcome|overdone|overtaken|\
overthrown|paid|pled|proven|\
put|quit|read|rid|ridden|\
rung|risen|run|sawn|said|\
seen|sought|sold|sent|\
set|sewn|shaken|shaven|\
shorn|shed|shone|shod|\
shot|shown|shrunk|shut|\
sung|sunk|sat|slept|\
slain|slid|slung|slit|\
smitten|sown|spoken|sped|\
spent|spilt|spun|spit|\
split|spread|sprung|stood|\
stolen|stuck|stung|stunk|\
stridden|struck|strung|\
striven|sworn|swept|\
swollen|swum|swung|taken|\
taught|torn|told|thought|\
thrived|thrown|thrust|\
trodden|understood|upheld|\
upset|woken|worn|woven|\
wed|wept|wound|won|\
withheld|withstood|wrung|\
written"
 
if [ "$1" = "" ]; then
 echo "usage: `basename $0` <file> ..."
 exit
fi
 
egrep -n -i --color \
 "\\b(am|are|were|being|is|been|was|be)\
\\b[ ]*(\w+ed|($irregulars))\\b" $*

passivecount=

passivecount=0
for arg in $*; do
    passivehere=$(egrep -c -i \
 "\\b(am|are|were|being|is|been|was|be)\
\\b[ ]*(\w+ed|($irregulars))\\b" $arg)
    passivecount=$((passivecount + passivehere))
done

# ----------------- DUPLICATES ---------------------

echo -e "\033[1;32mChecking for duplicates...\033[0m"


dupcount=0
for arg in $*; do
    ln=0
    lastword=
    while IFS= read -r line; do
        line=$(echo $line tr '[:upper:]' '[:lower:]')

        words=$(sed 's/ \W/\n/g' <<<"$line")
        
        for word in $words; do
            if [ "$word" = "$lastword" ]; then
                echo -e "$arg:$ln: \033[1;31m$word\033[0m"
                ((dupcount++))
            fi
            lastword=$word
        done
        ((ln++))
    done < $arg
done

# ------------------ RESULTS ---------------------

echo "Weasel words: $weaselcount"
echo "Passive tone: $passivecount"
echo "Duplicates: $dupcount"